name: Resume Backend Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'resume_backend/lambda_function.py'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip Lambda function
      run: |
        cd resume_backend
        zip -r lambda_function_payload.zip lambda_function.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Fetch bucket name from SSM
      id: fetch-bucket
      run: |
        BUCKET_NAME=$(aws ssm get-parameter --name "/resume_website/prod/s3/back_end/bucket_name" --query "Parameter.Value" --output text)
        # echo "::set-output name=bucket::${BUCKET_NAME}"
        echo "bucket=$BUCKET_NAME" >> $GITHUB_OUTPUT

    - name: Upload to S3
      run: |
        aws s3 cp lambda_function_payload.zip s3://${{ steps.fetch-bucket.outputs.bucket }}/backend/lambda_function_payload.zip
